name: GitHub metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: "master"}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Get languages
        uses: lowlighter/metrics@latest
        with:
          user: DaanKorver
          template: classic
          base: activity, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%

      - name: 🎖 Get Contributors
        uses: lowlighter/metrics@latest
        with:
          # ... other options
          plugin_contributors: yes
          plugin_contributors_base: ""           # Base reference (commit, tag, branch, etc.)
          plugin_contributors_head: master       # Head reference (commit, tag, branch, etc.)
          plugin_contributors_ignored: bot       # Ignore "bot" user
          plugin_contributors_contributions: yes # Display number of contributions for each contributor




